name: recipe_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.7
  path: ^1.8.2
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/edit.png
    - assets/image/food_logo.jpg
    - assets/image/fruit_sando.jpg
    - assets/image/miso_soup.jpg
    - assets/image/tomyam_udang.jpg
    - assets/image/carbonara_udon.jpg
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf